openapi: 3.0.0
info:
  title: bike
  description: Bicicletário
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/unirio-ca4/boke/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/unirio-e61/VaDeBike/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: usuario
  description: Lida com interações relacionadas aos usuarios do sistema
- name: equipamento
  description: Gerencia o equipamento do sistema
- name: pagamento
  description: Lida com requisições de pagamento
- name: email
  description: Envia e-mail ao cliente
paths:
  /usuario/funcionario/insereFuncionario:
    post:
      tags:
      - usuario
      description: Insere um novo funcionário
      operationId: insereFuncionario
      requestBody:
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/FuncionarioDTO'
        required: true
      responses:
        "201":
          description: "Funcionário editado, retorna lista de funcionários"
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FuncionarioDTO'
        "400":
          description: Funcionario não inserido
        "500":
          description: Erro interno no sistema
  /usuario/funcionario/editaFuncionario:
    post:
      tags:
      - usuario
      description: Edita um novo funcionário
      operationId: editaFuncionario
      requestBody:
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/FuncionarioDTO'
        required: true
      responses:
        "201":
          description: "Funcionário editado, retorna lista de funcionários"
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FuncionarioDTO'
        "400":
          description: Funcionario não inserido
        "500":
          description: Erro interno no sistema
  /usuario/funcionario/excluiFuncionario:
    post:
      tags:
      - usuario
      description: Exclui um novo funcionário
      operationId: excluiFuncionario
      requestBody:
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/MatriculaDTO'
        required: true
      responses:
        "204":
          description: "Funcionário excluído, retorna lista de funcionários"
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FuncionarioDTO'
        "400":
          description: Funcionario não encontrado
        "500":
          description: Erro interno no sistema
components:
  schemas:
    DadosCliente:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
        senha:
          type: string
        cpf:
          type: string
        data_nascimento:
          type: string
          format: date
        nacionalidade:
          type: string
          enum:
          - Estrangeiro
          - Brasileiro
        foto_documento:
          type: string
          format: base64
        passaporte:
          allOf:
          - $ref: '#/components/schemas/Passaporte'
    Passaporte:
      type: object
      properties:
        pais:
          pattern: "[A-Z]{2}"
          type: string
        numero:
          type: string
        data-validade:
          type: string
          format: date
    CartaoDeCredito:
      type: object
      properties:
        numero:
          type: string
          format: "/d{16}"
        nome:
          type: string
        codigo-seguranca:
          type: string
          format: "/d{3,4}"
        data-validade:
          type: string
          format: date
    Cliente:
      allOf:
      - type: object
        properties:
          id:
            type: string
            format: uuid
          foto_documento:
            type: string
          status:
            type: string
            format: "enum['ATIVO', 'INATIVO', 'CONFIRMACAO_PENDENTE']"
      - $ref: '#/components/schemas/DadosCliente'
    FuncionarioDTO:
      required:
      - email
      - funcao
      - idade
      - matricula
      - nome
      type: object
      properties:
        matricula:
          type: string
          example: INSERIR EXEMPLO
        email:
          type: string
          example: email@dominio.com
        nome:
          type: string
          example: Arthur Campbell
        idade:
          type: integer
          example: 18
        funcao:
          type: string
          format: "enum['administrativo', 'reparador']"
          example: administrativo
    MatriculaDTO:
      type: object
      properties:
        matricula:
          type: string
          example: INSERIR EXEMPLO DE MATRICULA
